[package]
org = "oneblok"
name = "backend"
version = "0.1.0"
distribution = "2201.12.7"

[build-options]
observabilityIncluded = true

[[platform.java21.dependency]]
groupId = "org.postgresql"
artifactId = "postgresql"
version = "42.7.2"